Vagrant.configure("2") do |config|
# Definición de FW
  config.vm.define "fw" do |fw|
    fw.vm.box = "bento/ubuntu-22.04"
    fw.vm.hostname = "FW"
    fw.vm.network "public_network", bridge: "enp6s0", ip: "192.168.1.254", netmask: "255.255.255.0"
    fw.vm.network "private_network", ip: "192.168.56.254", netmask: "255.255.255.0"
    # eliminar default gw en eth0 – red NAT creada por defecto
    fw.vm.provision "shell",
        run: "always",
        inline:  "ip route del default"    
    # default router
    fw.vm.provision "shell",
        run: "always",
        inline: "ip route add default via 192.168.1.1"
    fw.vm.provider "virtualbox" do |vb|
        vb.name = "FW"
        # vb.gui = true
        vb.memory = "1024"
        vb.cpus = 1
        vb.linked_clone = true
        vb.customize ["modifyvm", :id, "--groups", "/FW-Server"]
    end
  end

# Definición del servidor interno
  config.vm.define "server" do |server|
    server.vm.box = "bento/ubuntu-22.04"
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.56.253", netmask: "255.255.255.0"
    server.vm.synced_folder "./www", "/var/www/html"
    server.vm.provision "shell", path: "lamp_generico.sh"
    # eliminar default gw en eth0 – red NAT creada por defecto
    server.vm.provision "shell",
        run: "always",
        inline:  "ip route del default"   
    # default router
    server.vm.provision "shell",
        run: "always",
        inline: "ip route add default via 192.168.56.254"
    server.vm.provider "virtualbox" do |vb|
        vb.name = "server"
        # vb.gui = true
        vb.memory = "1024"
        vb.cpus = 2
        vb.linked_clone = true
        vb.customize ["modifyvm", :id, "--groups", "/FW-Server"]
    end
  end
end
