Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

# WEB
  (1..3).each do |i|
    config.vm.define "web0#{i}" do |node|
        node.vm.hostname = "web0#{i}"
        node.vm.network "private_network", ip: "192.168.56.5#{i}", netmask: "255.255.255.0"
        node.vm.synced_folder "./web0#{i}", "/var/www/html"
        node.vm.provision "shell", path: "apache.sh"
        node.vm.provider "virtualbox" do |vb|
            vb.name = "web0#{i}"
            # vb.gui = true
            vb.memory = "1024"
            vb.cpus = 1
            vb.linked_clone = true
            vb.customize ["modifyvm", :id, "--groups", "/Cluster"]
        end
    end
  end
end
